server:
  port: 8080
  servlet:
    contextPath: ""
# enable all actuator endpoints
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: 
        - "*"
        - hystrix.stream
eureka:
  instance:
    status-page-url-path: ${server.servlet.contextPath}/actuator/health
spring:
  cloud:
    gateway:
      routes:
      - id: ui-svc-default
        uri: lb://ui
        predicates:
        - Path=/
        filters:
        - RedirectTo=307, /ui/
        # - RewritePath=/(?<segment>.*), /ui/$\{segment}
        - name: Hystrix
          args:
            name: ui-svc-default-fallback
            fallbackUri: forward:/uiFallback
      - id: ui-svc-welcome
        uri: lb://ui
        predicates:
        - Path=/*.*
        filters:
        - RedirectTo=307, /ui/
        # - RewritePath=/(?<segment>.*), /ui/$\{segment}
        - name: Hystrix
          args:
            name: ui-svc-welcome-fallback
            fallbackUri: forward:/uiFallback
      - id: ui-svc
        uri: lb://ui
        predicates:
        - Path=/ui/**
        filters:
        - name: Hystrix
          args:
            name: ui-svc-fallback
            fallbackUri: forward:/uiFallback
      - id: report
        uri: lb://report
        predicates:
        - Path=/report/**
        filters:
        - name: Hystrix
          args:
            name: report-svc-fallback
            fallbackUri: forward:/reportFallback
      - id: valid
        uri: lb://valid
        predicates:
        - Path=/valid/**
        filters:
        - name: Hystrix
          args:
            name: valid-svc-fallback
            fallbackUri: forward:/validFallback
      - id: disco-svc
        uri: lb://disco
        predicates:
        - Path=/disco
        filters:
        - RewritePath=/disco,/
        - name: Hystrix
          args:
            name: disco-svc-fallback
            fallbackUri: forward:/discoFallback
      - id: disco-svc-eureka
        uri: lb://disco
        predicates:
        - Path=/eureka/**
        filters:
        - name: Hystrix
          args:
            name: disco-svc-eureka-fallback
            fallbackUri: forward:/discoFallback
        # filters:
        # - RewritePath=/eureka/(?<segment>/?.*), /eureka/$\{segment}
      - id: config-svc
        uri: lb://config
        predicates:
        - Path=/config
        filters:
        - RewritePath=/config,/
      - id: htxdbd-svc
        uri: lb://htxdbd
        predicates:
        - Path=/hystrix/**
      - id: htxdbd-svc-webjars
        uri: lb://htxdbd
        predicates:
        - Path=/webjars/**
        # filters:
        # - RewritePath=/webjars/(?<segment>/?.*), /$\{segment}
      - id: zipkin
        uri: http://localhost:9411
        predicates:
        - Path=/zipkin/**
        # filters:
        # - RewritePath=/webjars/(?<segment>/?.*), /$\{segment}

        