server:
  port: 8761
  servlet:
    contextPath: ""
# enable all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    # name listed under application on the Eureka dashboard
    appname: ${spring.application.name}
logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF
